# Generated by Django 5.2.4 on 2025-07-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_answer_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guessed_letters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
