# Generated by Django 5.2.4 on 2025-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_guessed_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='winstreak',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
