# Generated by Django 5.2.4 on 2025-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_score_user_winstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
